import Head from 'next/head';
import List from '../component/list';
import axios from 'axios';

export default function Home({ data }) {
  const list = data.result.properties.elements;
  const { id } = data.result.properties.elements;

  return (
    <div>
      <Head>
        <title>List of properties</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <List list={list} key={id} />
      </main>

      <footer>&copy; Maria Cotofana</footer>
    </div>
  );
}

export const getServerSideProps = async (context) => {
  const baseUrl =
    process.env.NODE_ENV === 'production'
      ? 'https://properties-list-with-filter.vercel.app/'
      : 'http://localhost:3000/';
  const { data } = await axios.get(`${baseUrl}api/properties`);

  if (!data) {
    return {
      error: 'error, not found',
    };
  }

  return {
    props: { data },
  };
};
